# Generated by Django 5.0.6 on 2024-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, help_text='Введите содержимое', null=True, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='blog', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликовать блог?', verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, help_text='Количество просмотров блога', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блоговая запись>',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ('title',),
            },
        ),
    ]
