# Generated by Django 5.0.6 on 2024-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='blog/', verbose_name='Превью'),
        ),
    ]
