# Generated by Django 5.0.6 on 2024-07-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0, editable=False, help_text='Количество просмотров блога', verbose_name='Просмотры'),
        ),
    ]
