# Generated by Django 5.0.6 on 2024-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
