# Generated by Django 5.0.6 on 2024-07-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Введите номер версии', verbose_name='Номер версии')),
                ('name_version', models.CharField(help_text='Введите название версии', max_length=100, verbose_name='Название версии')),
                ('is_current_version', models.BooleanField(default=False, help_text='Установите текущую версию', verbose_name='Это текущая версия')),
                ('product', models.ForeignKey(help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продукта',
                'ordering': ('-version_number',),
            },
        ),
    ]
