# Generated by Django 4.2.2 on 2024-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_cancel_publication', 'Can cancel publication'), ('can_change_description', 'Can change the description'), ('can_change_category', 'Can change the category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Выберите статус публикации', verbose_name='Опубликовано'),
        ),
    ]
